apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: z3y2m7v8w-go 
  janus-idp.io/tekton: z3y2m7v8w-go
  backstage.io/kubernetes-id: z3y2m7v8w-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: z3y2m7v8w-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml