apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: z3y2m7v8w-go
  janus-idp.io/tekton: z3y2m7v8w-go
  backstage.io/kubernetes-id: z3y2m7v8w-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: z3y2m7v8w-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
